title: Smokes and Farts for Shits and Giggles
author: Masstat2
email: masstat.jv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My random musings and prognostic views on anything that catches my fancy!
theme: minima

# social links
twitter_username: JvMasstat # DO NOT include the @ character, or else the build will fail!
github_username:  Masstat2 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
